name = "popcicle"
version = "1.1.0"
target = "javascript"
description = "Simple to use, styleable popovers for Lustre"
licences = ["Apache-2.0"]
repository = { type = "github", user = "dinkelspiel", repo = "popcicle" }
links = [{ title = "Website", href = "https://popcicle.keii.dev" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.6.3 and < 5.0.0"
plinth = ">= 0.5.6 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
